### ISSUE TITLE
Nextcloud only offers v0.2.1 for download

### ISSUE THREAD

**Issue by MyNameIsRatchet** [nextcloud/twofactor_admin#295]
Hi,

I use this app for a long time now, but today I realized that the installed version is "0.2.1" and Nextcloud 26.0.4 says "This app is up to date". If I disable and remove the app, it's only possible to install the 0.2.1-version. In config.php was an exclusion for updating the twofactor_admin-app (via app_install_overwrite), I removed it, restarted - but no changes, I'm unallowed to download the current version 4.2.0.
Any ideas?

Thanks in advance
<img width="410" alt="Bildschirmfoto 2023-08-02 um 11 22 33" src="https://github.com/nextcloud/twofactor_admin/assets/40836975/cbda245c-560d-4d19-a20a-63e6e003e04a">

**Comment by MyNameIsRatchet** [comment]
UPDATE:
I figured it out, [this is related to this issue]([https://github.com/nextcloud/twofactor_admin/issues/294])) - 0.2.1 is the last released version without php min-version or php max-version.
I use PHP 8.4 - thats why I don't see the latest release. But I can see the 0.2.1 because it has no php-limitation.
Could you please fix that and maybe drop the old versions as they are unnecessary?

**Comment by ChristophWurst** [comment]
PHP8.2 is the latest PHP.

**Comment by MyNameIsRatchet** [comment]
You're right, my instance says v.8.2.8 - sorry. Do you have any idea why I can't download your app v.4.2.0?

**Comment by carsten-bock** [comment]
Hi, I do have the same problem. 
In short: 4.2.0 is marked as compatible with php 8.1 and lower. Is there a way to update this to work with php verion 8.2?

As Ratchet described:
Only Versoin 0.2.1 is offered to install and activate. This version doesn't work propperly with Nextcloud 27. Only the occ command ist working, no section under Securtiy to trigger a admin code via web interface. And after entering the code an internal server error occurs.
After installing verion 4.2.0 manually the app isn't able to be activated. The following errormessage is shown:
`App "Two-Factor Admin Support" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 8.1 is required.`
But php 8.2 is the recommend version to run Nextcloud 27. [see link](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html)
@ChristophWurst  could you please update the app to work with php 8.2 or verify that the app is compatible with php8.2 an mark it at the app portal?
I would really apreciate a quick fix. Many Thanks in advance.
Carsten

<img width="398" alt="admin" src="https://github.com/nextcloud/twofactor_admin/assets/144593726/42c8e775-1ba5-44df-ae6c-dbbb5e417fa3">

**Comment by Altahrim** [comment]
Hello,

The app is now compatible with PHP 8.2 (see #303). 
The update should appear soon :)

**Comment by carsten-bock** [comment]
Sorry for the late reply.
But I wanted to thank you for the fix. This is a realy helpful piece of software.
So thank you very much!
